### ISSUE TITLE
Installation requires a system that uses yum/apt-get

### ISSUE THREAD

**Issue by safonova** [KrishnaswamyLab/DiffusionEMD#1]
When installing ```DiffusionEMD``` on a slurm-based cluster, I ran into a long-winded error that essentially comes down to

> gcc -pthread -B /directory_redacted/conda_envs/environment_name/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/suitesparse -I/directory_redacted/conda_envs/environment_name/include/python3.7m -c build/temp.linux-x86_64-3.7/sparseqr._sparseqr.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/sparseqr._sparseqr.o
>     build/temp.linux-x86_64-3.7/sparseqr._sparseqr.c:540:29: fatal error: SuiteSparseQR_C.h: No such file or directory
>      #include <SuiteSparseQR_C.h>
>                                  ^
>     compilation terminated.
>     error: command 'gcc' failed with exit status 1

Apparently, one of the dependencies (sparseqr) is intended to be used on a system where you can install system packages using yum/apt-get. It's expecting to find a header file in a "standard" location, which is not present on the slurm-managed cluster. There was an issue raised about this a few years ago in the sparseqr github ([https://github.com/yig/PySPQR/issues/11](https://github.com/yig/PySPQR/issues/11)).

**Comment by atong01** [comment]
Should be able to fix this by relying on the scipy implementation of sparse interpolative decomposition. It seems like sparser has a number of dependency issues. I'll look into this eventually unless you'd like to take a crack at it.

**Comment by atong01** [comment]
Fixed by PR #3
