### ISSUE TITLE
How to get gradients

### ISSUE THREAD

**Issue by sgbaird** [KrishnaswamyLab/DiffusionEMD#4]
Is the idea for gradients that you have an embedding for which the L1-norm approximates the earth mover's distance, so all you need to use in other algorithms is the L1-norm to get gradients? (i.e L1-norm (also Manhattan and City Block distance) in [scipy.spatial.distance.cityblock](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cityblock.html) and then just np.sign for the gradient)

See [differentiation of 1-norm of a vector](https://math.stackexchange.com/questions/1395699/differentiation-of-1-norm-of-a-vector/1395709):
<img src=https://user-images.githubusercontent.com/45469701/128286525-7730f6e6-5722-4cc9-b1d1-f204c1621b1e.png width=500>

**Comment by sgbaird** [comment]
I'm now going through the ArXiv paper's Appendix C.1 _Gradients of the Diffusion EMD_. To use a distance function with an algorithm, sometimes you need to pass it a function that outputs two arguments given two input vectors, where the first output argument is a scalar distance, and the second output argument is the gradient. It would be awesome if this sort of functionality could be incorporated into the repository.

**Comment by atong01** [comment]
Yes the Appendix is the right place to look for this. I've been working on a pytorch implementation of the algorithm which can take advantage of its autograd functionality. In this implementation you should be able to differentiate through the DiffusionEMD to get gradients for the inputs. Can work on posting this in some branch while I polish it.
