### ISSUE TITLE
potential for transform() method

### ISSUE THREAD

**Issue by sgbaird** [KrishnaswamyLab/DiffusionEMD#6]
I noticed that transform() has a pass statement. Is this simply not implemented or is it more so that it's theoretically challenging (i.e. we don't know how to do it yet).

**Comment by atong01** [comment]
The paper has two implementations of DiffusionEMD which in the code we call `DiffusionCheb` (for the Chebyshev polynomial method) and `DiffusionTree` which directly approximates powers of the diffusion matrix. These different methods share some code which is implemented in the `DiffusionEMD` class which is parent to both of them. 

So the implementations can be found in either of the classes implementing DiffusionEMD which are currently Cheb and Tree (still working on GPU).
